require("personal-settings.plugins-setup")
require("personal-settings.core.options")
require("personal-settings.core.keymaps")
require("personal-settings.core.colorscheme")
require("personal-settings.plugins.comment")
require("personal-settings.plugins.nvim-tree")
require("personal-settings.plugins.lualine")
require("personal-settings.plugins.telescope")
require("personal-settings.plugins.nvim-cmp")
require("personal-settings.plugins.lsp.mason")
require("personal-settings.plugins.lsp.lspsaga")
require("personal-settings.plugins.lsp.lspconfig")
-- require("personal-settings.plugins.lsp.null-ls")
require("personal-settings.plugins.autopairs")
require("personal-settings.plugins.treesitter")
require("personal-settings.plugins.gitsigns")
